name: Feature Request
description: Suggest a new feature or enhancement for the Yoink SDK
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like the SDK to...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...
    validations:
      required: false
      
  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you would use this feature
      render: typescript
      placeholder: |
        const result = await sdk.newFeature({
          // your example here
        });
    validations:
      required: false
      
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit users?
      placeholder: This would improve...
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
      
  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - label: This would be a breaking change
          required: false
        - label: This can be implemented without breaking existing functionality
          required: false
          
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
      placeholder: Add any other context here
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am willing to contribute this feature (with guidance)
          required: false
